# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#platform :ios, '8.0'

target 'FIIT-PDT-Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FIIT-PDT-Project
  pod 'Mapbox-iOS-SDK'
  pod 'GEOSwift'
#  pod 'GEOSwiftMapboxGL'
#
#  # Networking
  pod 'Alamofire'
  pod 'SwiftyJSON'

end
