//
//  MapViewPresenter.swift
//  FIIT-PDT-Project
//
//  Created by Tomáš Anda on 24/10/2018.
//  Copyright (c) 2018 FIIT-PDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapViewPresentationLogic
{
  func presentSomething(response: MapView.Something.Response)
}

class MapViewPresenter: MapViewPresentationLogic
{
  weak var viewController: MapViewDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MapView.Something.Response)
  {
    let viewModel = MapView.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
